name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Copy build artifacts
        run: mkdir artifacts && cp bukkit/target/*.jar artifacts
      - name: Package artifacts
        uses: actions/upload-artifact@v3
        with:
          path: artifacts
